---
- hosts: all
  vars_files:
  - "../../defaults/main.yml"
  tasks:
  - include: "../../tasks/main.yml"
  handlers:
  - include: "../../handlers/main.yml"
  - name: Restart MySQL
    service: name=mysql state=restarted
    become: true
