- hosts: webservers
  user: root
  sudo: True
  vars_files:
    - vars.yml

  roles:
    - role: bbatsche.MySQL-Install
      db_admin: deploy
      db_pass: "{{mysql_root_password}}"
      env_name: "{{app_env}}"

  post_tasks:
    - name: Create deploy user for mysql
      mysql_user: 
        name: deploy
        host: "%"
        password: "{{mysql_root_password}}"
        priv: "*.*:ALL,GRANT"
        login_user: root
        login_password: ""

    - name: Remove the test database
      mysql_db:
        name: test
        state: absent
        login_user: deploy
        login_password: "{{mysql_root_password}}"

    - name: Ensure anonymous users are not in the database
      mysql_user: user='' host={{item}} state=absent
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Update mysql root password for all root accounts
      mysql_user: name=root host={{item}} password={{mysql_root_password}}
      with_items:
        - 127.0.0.1
        - ::1
        - localhost