- hosts: webservers
  user: root
  sudo: True
  vars_files:
    - vars.yml
  vars:
    deploy: deploy
    home_dir: /home/deploy

  roles:
    - role: rvm_io.rvm1-ruby
      tags: ruby
      rvm1_rubies: ['ruby-2.3.1']
      rvm1_default_ruby_version: 'ruby-2.3.1'
      rvm1_rvm_check_for_updates: False

  pre_tasks:
    - name: Install Linux packages
      action: apt pkg={{item}} state=present
      with_items:
        - autoconf
        - automake
        - bison
        - build-essential
        - curl
        - gawk
        - git-core
        - git
        - libxml2-dev
        - libffi-dev
        - libyaml-dev
        - libssl-dev
        - libsqlite3-dev
        - libgdbm-dev
        - libncurses5-dev
        - libreadline6-dev
        - libtool
        - libyaml-dev
        - nfs-common # make virtualbox faster
        - pkg-config
        - sqlite3
        - vim
        - zlib1g-dev
