---
- name: Install
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - libmysqlclient-dev
    - python-mysqldb
  become: yes
  register: mysql_install

- name: Install Percona Toolkit
  apt: package=percona-toolkit state=present
  become: yes

- name: Create Configuration File
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  become: yes
  notify: Restart MySQL

- include: lockdown.yml
  when: mysql_install | changed
